### ISSUE TITLE
How to launch local gbp instance?

### ISSUE THREAD

**Issue by jj-martinez** [enku/gentoo-build-publisher#1]
I'm interested in trying out and contributing to this project but I'm having trouble figuring out how to launch it.

Could you provide me some notes on how to get started? If you want to provide some terse notes here I'm happy to extend them and add them to the README via pull request after I get this working.

**Comment by enku** [comment]
Hi @jj-martinez  for some reason I'm just seeing this issue (I need to check my email settings). Coincidentally I have just recently added a [howto](https://github.com/enku/gentoo-build-publisher/blob/master/docs/how-to-install.md) for installing GBP. I really hope you can give it a try and follow up in #1 with any questions/comments.  Thanks.

**Comment by enku** [comment]
Closing this out as there is now an install guide and there have been no further questions.
